name: test_task
description: Changes the background color to a random one on tap.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  effective_dart: ^1.0.0

flutter:
  uses-material-design: true
